USE [Containers]
GO


INSERT INTO dbo.Regions(Name) VALUES('Zona Norte')
INSERT INTO dbo.Regions(Name) VALUES('Zona Sur')
INSERT INTO dbo.Regions(Name) VALUES('Zona Este')
INSERT INTO dbo.Regions(Name) VALUES('Zona Oeste')
INSERT INTO dbo.Regions(Name) VALUES('Zona Externa')


INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(184,'A&E PRODUCTS','ZIP CALPULES KM 7 CARRETERA A LA LIMA',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(95,'ACCESORIOS PARA VAPOR','8 AV 2 CALLE S.E. NO. 5 BO. SANTA ANITA SAN PEDRO SULA, HONDURAS',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(7,'ACE FASHION HONDURAS LTD.','ZONA LIBRE DE PUERTO CORTES EDIF. # 2',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(851,'ACME MCCRARY','ZOLI ZIP CHOLOMA II, CARRETERA A LA JUTOSA, KM 2, CHOLOMA, CORTES',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(225,'ADHESA S.A.','CHOLOMA, HONDURAS EDIFICIO 3',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(823,'ADUANA AGUAS CALIENTES','DEPARTAMENTO DE OCOTEPEQUE FRONTERA ENTRE HONDURAS Y GUATEMALA',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(871,'ADUANA EL FLORIDO','DEPARTAMENTO DE COPÁN FRONTERA ENTRE HONDURAS Y GUATEMALA',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(834,'ADUANA EL POY','DEPARTAMENTO DE OCOTEPEQUE FRONTERA ENTRE HONDURAS Y EL SALVADOR',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(900,'ADUANA LA MESA','AEROPUERTO INTERNACIONAL RAMÓN VILLEDA MORALES, SAN PEDRO SULA, DEPARTAMENTO DE CORTÉS.',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(227,'ADUANA LAS MANOS','DEPARTAMENTO DEL PARAISO FRONTERA ENTRE HONDURAS Y NICARAGUA',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(838,'ADUANA PUERTO CORTES','DEPARTAMENTO DE CORTÉS',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(356,'AFAISA','ZIP RIO BLANCO NAVE #14',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(142,'AGENCIA J.E. HANDAL','HONDURAS, CHOLOMA, ZONA LIBRE, KM. 2.6 ADELANTE DE LAS CASETAS DE PEAJE, AUTOPISTA A PUERTO CORTÉS',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(635,'AIMAR LOGISTICS','ZIP SAN JOSE 20 Y 27 CALLE 2ND ANILLO PERIFERICO SPS',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(1107,'AKH S.A.','PARQUE INDUSTRIAL GREEN VALLEY NACO, CORTÉS HONDURAS',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(226,'ALFATEX DE HONDURAS','NULL',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(1063,'ALIANZA JOVEN HONDURAS USAID','SAN PEDRO SULA. EDIFICIO LA PLAZA, LOCAL 13-B, 1RA Y 2DA AVE. NORESTE.',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(957,'ALIMENTOS ABC','CHOLOMA, CORTES',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(1043,'ALMAHSA','SPS 33 CALLE SECTOR EL POLVORIN,FRENTE COMPLEJO MACRO BODEGAS; ANTIGUO CENTRO UNILEVER',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(589,'ALPLA HONDURAS','BOULEVAR SPS ATRAS DE PLASTICOS INDUSTRIALES',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(1020,'ALTIA BUSSINESS PARK','ZONA LIBRE ALTIA',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(1000,'ALUCOM','14 AVENIDA NE, SAN PEDRO SULA',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(1162,'AMEER APPAREL','ZIP BÚFALO, CARRETERA A VILLANUEVA, CORTÉS.',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(1045,'ANDURO MANUFACTURING','ZONA LIBRE ASTRO SAN PEDRO SULA, CORTÉS HONDURAS',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(99,'APTEX, S.A.','ZIP FORMOSA',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(1053,'ARCHROMA HONDURAS S.A','ZOLI INHDELVA NORTE 800 MTS. CARRETERA A LA JUTOSA',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(1091,'ARROCERA CHOLOMEÑA','',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(259,'ASTRO CARTON','600 MTS. BOULEVARD, COL. FELIPE ZELAYA',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(796,'ATLANTIC PACKAGING S.A.','ZOLI INHDELVA NORTE 800 MTS. CARRETERA A LA JUTOSA',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(434,'AUTO SERVICIOS TONNY','COL. PRIMAVERA CALLE PRINCIPAL, EL PROGRESO, YORO',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(945,'AVERY DENNISON RIS HONDURAS S DE R.L.','BLDG 25A ZIP BUFALO INDUSTRIAL PARK VILLANUEVA CORTES',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(866,'BAEK HYANG','ZOLI PARQUE REAL',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(951,'BANG SAN HONDURAS','COL. GUANCHÍAS, KMT 2 CARRETERA SANTA RITA, EL PROGRESO, DEPARTAMENTO DE YORO.',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(1059,'BARRIO MEDINA','BARRIO MEDINA, SAN PEDRO SULA',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(477,'BAY ISLAND SPORTSWEAR','ZIP SAN JOSE',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(933,'BIJAO','CORTES HONDURAS',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(246,'BOLLAG INTERNATIONAL DE HONDURAS','ZONA LIBRE BOLLAG INTERCORP CHOLOMA, CORTÉS HONDURAS',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(1072,'BRITISH CARE CHEMICALS','ZOLI INHDELVA NORTE 800 MTS. CARRETERA A LA JUTOSA',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(1007,'BROOMS AND MOOPS','CHOLOMA CORTES FRENTE A KATIVO',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(217,'BUSINESS SOLUTION INTERNATIONAL (BSI)','COL. LAS MERCEDES, B:A #16, SAN PEDRO SULA',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(1139,'CADMUS','',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(1012,'CAFE MONTECRISTO','VILLANUEVA CORTES',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(145,'CAN & CAN HONDURAS. S.A.','ZOLI CONTINENTAL',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(876,'CARACOL KNITS','ZONA LIBRE EL CARACOL KM. 45, AL SUR DE SAN PEDRO SULA KM. 200, CARRETERA A TEGUCIGALPA, POTRERILLOS',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(1131,'CARGILL DE HONDURAS','BOULEVARD HACIA ARMENTA, ALTIA BUSSINESS PARK, TORRE 3, PISO 6 SAN PEDRO SULA, HONDURAS',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(1024,'CARIBEX HONDURAS','',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(917,'CARTEX MANUFACTURERA','',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(221,'CARTONERA EGO','VILLANUEVA,CORTES,DESVIO A LA CAÑADA FTE. A PROGCARNE',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(216,'CARTONERA NACIONAL S.A. (CANASA)','SALIDA A CHAMELECON, SAN PEDRO SULA',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(675,'CARTONES DE SULA S.A. DE C.V.','CARRETERA VIEJA A LA LIMA 2 CALLE 13 AVE CONTIGUO A YKK',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(815,'CASPIAN','ZOLI INHDELVA, CHOLOMA CORTES, HONDURAS',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(955,'CEIBA TEXTIL','NULL',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(382,'CELIO S.A.','1 AVENIDA 35-21Z12 COL EL CARMEN TEL 502 2442-0167 AL 69',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(818,'CENTRAL TEXTILES S.A. DEC.V.','DOS CAMINOS VILLANUEVA',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(1092,'CENTROQUIM DE HONDURAS','ZOLI TECNO SUPPLIER',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(80,'CENTURY HONDURAS','KM. 7 CARRETERA A LIMA, FRENTE A DESARROLLO METLICOS',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(1034,'CERVECERIA HONDUREÑA','NULL',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(459,'CHIQUITA','PTO CORTES',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(1052,'CHOLOMA CORTES','CHOLOMA CORTES',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(204,'CINTAS DE HONDURAS S.A','CARRETERA HACIA MUELLE DE CABOTAJE, LA CEIBA ATLANTIDA',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(1176,'CIRSA HONDURAS','ZONA LIBRE CIRSA HONDURAS BLVD. DEL SUR KM 16 SECTOR DOS CAMINOS, ENTRADA RESIDENCIAL LA JOYA VILLANUEVA, CORTES, SN, HONDURAS ',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(884,'CLOVER BRAND','NULL',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(794,'COATS DE HONDURAS','ZOLI INHDELVA ESTE 800 MTS. CARRETERA A LA JUTOSA',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(1021,'COATS II','ZIP CHOLOMA II',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(1112,'COATS INHDELVA NORTE','NULL',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(1039,'COIRSA','NULL',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(1014,'COLON','NULL',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(1047,'COLONIA SAN CARLOS','CHOLOMA, CORTES',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(86,'COLTEL','SAN PEDRO SULA',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(1177,'COLTEX','EDIFICIO 3 ZIP BUFALO, VILLANUEVA, CORTÉS, HONDURAS, C.A.',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(863,'COMAYAGUA','COMAYAGUA',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(982,'COMAYAGUELA','NULL',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(368,'COMIDAS TIPICAS/ROBERTO CONTRERAS','ZONA VIVA 15 AVE 11CALLE BARRIO SUYAPA S.PS HONDURAS',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(797,'COMP AIR SERVICE','ZOLI INHDELVA SUR 800 MTS. CARRETERA A LA JUTOSA',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(412,'CONDOR S.A.','',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(892,'CONFECCIONES ATLANTIDA','NULL',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(341,'CONFECCIONES DEL VALLE','CARRETERRA A TEGUCIGALPA ZIP BUENA VISTA',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(865,'CONFECCIONES DOS CAMINOS','NULL',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(206,'CONFECCIONES LA LIBERTAD','KM34, CRRT S. JUAN OPICO, LA LIBERTAD, EL SALVADOR',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(132,'CONFECCIONES MONZINI, S.A.','ANILLO PERIFERICO ZOLI LA CAÑADA',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(488,'CONFECCIONES ROSSY','SAN PEDRO SULA',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(373,'CONSOLIDADOS 807','ZOLI EL CARMEN',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(1109,'CONSORCIO RIO MANTARO','NULL',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(1035,'CONTRATISTAS UNIDOS','ZOLI INHDELVA NORTE 800 MTS. CARRETERA A LA JUTOSA',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(906,'COPAN','NULL',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(901,'COPROVA','NULL',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(895,'CORAL KNITS','ZONA LIBRE EL CARACOL KM. 45, AL SUR DE SAN PEDRO SULA KM. 200, CARRETERA A TEGUCIGALPA, POTRERILLOS',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(1174,'CORANORTE','A ORILLA DE CARRETERA, SECTOR BARACOA RIO BLANQUITO',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(192,'CORMAR DE HONDURAS','19 AVE 2DA CALLE ZOLI EL CARMEN',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(950,'CORPORACION DINANT','NULL',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(176,'CORPORACION HRC','PTO CORTES',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(1095,'CORSULA','NULL',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(766,'CORUMO INTERNACIONAL S. DE R.L.','BOULEVARD DEL SUR,300 MTS. ANTES DEL PEAJE CONTIGUO A GASOLI',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(854,'COSTA RICA','NULL',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(198,'COSTURAS, S.A. DE C.V.','ZOLI AMARATECA, TEGUCIGALPA',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(904,'COTTON WIDES','NULL',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(841,'CROWLEY LOGISTIC','ZOLI INHDELVA ESTE 800 MTS. CARRETERA A LA JUTOSA',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(612,'DACOTRANS','PORTUARIA PUERTO CORTES CONSOLIDADORA',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(979,'DELFIGEN','ZIP BUFALO',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(1123,'DELPHI AUTOMOTIVE SYSTEMS','NULL',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(902,'DELTA APPAREL','NULL',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(299,'DHL (HONDURAS) S.A. DE C.V.','COMPLEJO INDUSTRIAL CALPULES S.P.S, BODEGA #5',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(616,'DICKIES DE HONDURAS S.A','ZOLI SAN MIGUEL VI KM 15 1/2 RIO NANCE',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(515,'DIPROSA','50 MTS DESPUES DEL UNIVERSIDAD CATOLICA, CARRETERA AL BATALLON',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(803,'DIRECT SHIP AMERICAS','ZOLI INHDELVA SUR 800 MTS. CARRETERA A LA JUTOSA',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(182,'DISSI IMPORT','ZIP RIO BLANCO CARRETERA A PTO CORTES',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(491,'DISTRIBUIDORA LA BOBINA','ZONA LIBRE EL CACAO KM3 BOULEVARD DEL SUR SAN PEDRO SULA',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(998,'DMG COLOR','CARRETERA A TICAMAYA',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(71,'DRAGON MAYA, S.A.','ZOLI INHDELVA NORTE 800 MTS. CARRETERA A LA JUTOSA',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(795,'DUNLAP SUMBRAND','ZOLI INHDELVA NORTE 800 MTS. CARRETERA A LA JUTOSA',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(914,'E Y C REPRESENTACIONES','BARRIO PAZ BARAHONA SPS',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(857,'E.M. ADAMS','ZOLI INHDELVA NORTE 800 MTS. CARRETERA A LA JUTOSA',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(294,'ECA DE CENTROAMERICA','ZOLI ZIP BUFALO, VILLANUEVA CORTES',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(160,'EDWARD RICARDO BANEGAS','COL. SATELITE 1 ETAPA, ENTRADA AGUA AZUL B#84',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(990,'EL FLORIDO COPAN','NULL',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(965,'EL PROGRESO','NULL',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(819,'EL SALVADOR','SALVADOR',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(240,'ELCA S.A DE C.V','ENTRADA COL. LA MORA COSTADO N.E. DE ZIP CHOLOMA',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(105,'ELCATEX, S.A.','CARRETERA A PUERTO CORTÉS, COSTADO NOR-OESTE DE ZIP CHOLOMA CHOLOMA, CORTÉS, HONDURAS',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(199,'ELECTRONIC SERVICE, S.A.','ZOLI ZIP SAN JOSE, SAN PEDRO SULA; HOND',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(1048,'ELECTROQUIMICAS DE HONDURAS','ZOLI PTO CORTES',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(625,'ELIAS J KATTAN & CIA','ATRAS DE LA CATEDRAL 1 Y 2 CALLE SPS',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(1040,'EMEC','NULL',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(885,'EMPIRE ELECTRONICS HONDURAS','NULL',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(1104,'EMPRESA DE MATERIALES TEXTILES','ZOLI INHDELVA NORTE 800 MTS. CARRETERA A LA JUTOSA',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(1121,'ENERCO','ZOLI INHDELVA SUR 800 MTS. CARRETERA A LA JUTOSA',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(16,'ENSAMBLES INDUSTRIALES, S.A.','',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(165,'ENTRETELAS Y TEXTILES','ZOLI INHDELVA NORTE 800 MTS. CARRETERA A LA JUTOSA',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(1032,'ETHAN ALLEN','A ORILLAS DE CARRETERA A TICAMAYA,',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(353,'EUHA HONDURAS S.A. DE C.V.','ZONA LIBRE REAL, NAVE #7',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(264,'EUROMODAS','KILOMETRO 2 SALIDA VIEJA A LA LIMA',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(1060,'EXIID INTERNACIONAL','NULL',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(1126,'FABRIC BINDINGS INDUSTRIES','ZOLI INHDELVA ESTE 800 MTS. CARRETERA A LA JUTOSA',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(962,'FABRICA DE CHICLES Y CONFITES VENUS','NULL',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(1105,'FABRICA DE EMBUTIDOS EUROPEA SA CV','NULL',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(1098,'FABRICA DE ESPECIAS DON JULIO','SAN PEDRO SULA',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(421,'FABRICA DE ROPA MONTECARLO','7 CALLE 17 Y 18 AVE.NO#1706 SPS',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(1144,'FACHADA CARPINTERIA DE ALUMINIO SRL','NULL',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(108,'FASHION MART DE HONDURAS','COL RIO BLANCO ATRAS DE GASOLINERA DEPESA BOLV DEL NORTE',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(1130,'FERTILIZANTES DE CENTROAMERICA','3 AVE 15 Y 16 CALLE B. LA GUARIDA SPS',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(76,'FIBERTEX','ZIP SAN JOSE SAN PEDRO SULA',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(1142,'FIBRAS Y TEXTILES','COL. LOPEZ ARELLANO',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(245,'FINOS TEXTILES DE CENTROAMERICA S.A','ZOLI ZIP CHOLOMA II, CARRETERA A LA JUTOSA, KM 2, CHOLOMA, CORTES',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(103,'FIVARO','VILLANUEVA CORTES',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(1141,'FORMAS TERMICAS','NULL',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(1124,'FRANCIS APPAREL','NULL',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(1089,'GARAN BUENA VISTA','NULL',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(186,'GARAN SAN JOSE, S.A DE C.V.','ZOLI ZIP SAN JOSE, SPS, HONDURAS',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(19,'GARMAX OF CORTES S. DE R.L','ZOLI DE PUERTO CORTES, EDIF. # 8 CORTES, HOND.',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(190,'GBM','SAN PEDRO SULA',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(833,'GENESIS APPAREL','NULL',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(141,'GILDAN ACTIVEWEAR','ZOLI ZIP RIO NANCE',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(860,'GILDAN CHOLOMA','NULL',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(1023,'GILDAN CHOLTEX','ZOLI GILDAN CHOLOMA TEXTILES, RIO NANCE 15.5 KM CARRETERA A PUERTO CORTES',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(1037,'GILDAN HONDURAS DISTRIBUTION','NULL',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(1079,'GILDAN HONTEX','ZIP SAN MIGUEL VI, RIO NANCE, CHOLOMA, CORTES.',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(893,'GILDAN HOSIERY','ZOLI GILDAN CHOLOMA TEXTILES RIO NANCE, 15.5 KM A PTO CORTES',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(1041,'GILDAN MAYAN TEXTILES','ZOLI GILDAN CHOLOMA TEXTILES RIO NANCE, 15.5 KM A PTO CORTES',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(255,'GILDAN SAN JOSE','ZOLI SAN JOSE EDIFICIO F-11, SAN PEDRO SULA',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(257,'GILDAN SAN MIGUEL','ZIP CHOLOMA, CHOLOMA, CORTES, HONDURAS',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(1015,'GILDAN VILLANUEVA','VILLANUEVA CORTES',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(106,'GLORY GARMENT S DE R.L','ZOLI ZJP RIO BLANCO',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(1038,'GOLDEN QUIMICA','ZOLI INHDELVA ESTE CHOLOMA CORTES',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(603,'GREEN VALLEY INDUSTRIAL PARK','KM 23 CARRETERA A OCCIDENTE QUIMISTAN SANTA BARBARA',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(262,'GRUPO AVIARA','LAFONTAINE N.95 COL POLANCO',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(996,'GRUPO RECICLADORES','NULL',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(1119,'GRUPO TRANSMERQUIM','SEGUNDO ANILLO DE CIRCUNVALACION 300 MTS DE CORP. FLORES',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(242,'GUANTES SUREÑOS','ZONA LIBRE CONTINENTAL LA LIMA HONDURAS',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(847,'GUATEMALA','NULL',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(379,'GUILLERMO KATTAN','COLO RIO DE PIEDRAS SAN PEDRO SULA HONDURAS',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(878,'HANES CHOLOMA II','ZIP CHOLOMA II',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(57,'HANES CHOLOMA S. DE R.L. (54)','ZIP CHOLOMA, COL LA MORA CHOLOMA, CORTES; HONDURAS',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(513,'HANES CHOLOMA S. de R.L. AA','ZIP VILLANUEVA',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(418,'HANES CHOLOMA, S. DE R.L. (F7)','ZIP CHOLOMA, COL LA MORA CHOLOMA, CORTES; HONDURAS',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(24,'HANES INK','ZOLI INHDELVA NORTE CHOLOMA CORTES',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(837,'HANES VILLANUEVA','ZIP ZOLI VILLANUEVA, VILLANUEVA',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(825,'HANIL HONDURAS','HANIL HONDURAS',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(275,'HANSOLL HONDURAS,S.A. DE C.V.','KM.22.5 CARRETERA A OCC.NACO QUIMISTAN SANTA BARBARA',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(185,'HILOS A & E DE HONDURAS','COSTADO N.O. DE ZIP CHOLOMA CONTIGUO A COLONIA LA MORA',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(88,'HILOS Y MECHAS','BOULEVAR DEL NORTE, SECTOR CERVECERIA',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(135,'HMM DE HONDURAS','ZONA LIBRE HMM DE HONDURAS',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(822,'HONDUAMERICAN','HONDUAMERICAN',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(967,'HONDUCHEM','NULL',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(207,'HONDURAS APPAREL INDUSTRY, S.A.(HAISA)','ZIP FORMOSA, CARRT. A OCCI, COFRADIA',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(980,'HONDURAS SPINNING','ZOLI COFRADIA',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(94,'HUGGER DE HONDURAS','ZOLI ZIP SAN JOSE',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(21,'IDEA HONDURAS, S. DE R.L. DE C.V.','EDIFICIO 23 ZIP BUFALO, VILLANUEVA,VILLANUEVA CR HONDURAS',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(332,'IMPRENTA PHOENIX','ZOLI ZIP HONDURAS CARRETERA A CORTES',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(73,'INDEX','7-8 CALLE, 4AVE BO. GUAMILITO, SPS, HONDURAS',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(280,'INDUSTRIA CONFITERA CENTROAMERICANA','NULL',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(1106,'INDUSTRIA HONDUREÑA','NULL',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(183,'INDUSTRIAS CONTINENTAL','ZOLI INCO CARRETERA A VILLANUEVA 300MTS ADELANTE DE PRONORSA',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(102,'INDUSTRIAS COREA (INDUCO)','SAN PEDRO SULA, CARRETERA A PUERTO CORTÉS',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(639,'INDUSTRIAS MERLET S.A DE C.V.','CALLE CIRCUNVALACION POLIGONO A LOTE 3-4 LA LAGUNA',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(685,'INDUSTRIAS NORTEAMERICANAS','EDIFICIO NO.9., ZOLI HONDURAS INDUSTRIAL PARK',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(1088,'INDUSTRIAS PINARES','NULL',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(392,'INDUSTRIAS TABONY','ZIP CHOLOMA, ENTRADA COL LA MORA',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(26,'INDUSTRIAS YANG','ZIP RIO BLANCO, KM 7 CARRETERA A PTO CORTES',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(1,'INMOBILIARIA HONDUREÑA DEL VALLE','ZONA LIBRE INHDELVA, CHOLOMA, CORTES HONDURAS',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(265,'INTERMODA, S.A.','KM.1 AUTOPISTA AL AEROPUERTO, SPS',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(558,'INVEMA','900 MTS CARRETERA EL ZAPOTAL',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(193,'INVERSIONES APOLO S.A','2 CALLE 22/23 AVE S.O NO.227 S.P.S',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(875,'INVERSIONES EL CARMEN','NULL',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(978,'INVERSIONES EMCO','NULL',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(1064,'INVERSIONES INALMA','KM 5 CARRETERA PUERTO CORTES 200 METROS AL SUR ZIP HONDURAS CHOLOMA CORTES HONDURAS',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(910,'INVERSIONES LUNA','27 CALLE AVE. NEW ORLEANS ESQUINA OPUESTA AGENCIA LA MUNDIAL',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(918,'INVERSIONES MATERIALES S.DE R.L. DE C.V.','RIO BLANCO CARRETERA HACIA ALDEA EL ZAPOTAL SAN PEDRO SULA',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(523,'INVERSIONES NOLAY','ZOLI EL CARMEN',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(1013,'INVERSIONES PEREZ VELIZ/ JHON JAIRO','CHOLOMA, CORTES',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(811,'INVERSIONES SOLARIS TIGO','ZOLI INHDELVA SUR 800 MTS. CARRETERA A LA JUTOSA',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(1173,'INVESSA S. DE R.L.','ZIP RIO BLANCO',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(1011,'INVEX','RIO BLANQUITO CARRETERA A PTO. CORTES',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(1042,'ISOCHEM COLORS Y CHEMICALS','NULL',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(760,'ITALIAN INDUSTRIAL AGENCY','ZOLI INHDELVA ESTE 800 MTS. CARRETERA A LA JUTOSA',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(315,'IVY GARMENT','ZOLI RIO BLANCO, EDIFICIO #21',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(161,'J.E. HANDAL S.A DE C.V','COL. MODERNA #1706 7 CALLE 17-18 AVENIDA',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(59,'JASPER HONDURAS','ZOLI HONDURAS KM 5 CARRETERA PUERTO CORTES EDIF 16-19, CHOLOMA, CORTES, HONDURAS',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(511,'JB HONDURAS','KM 4/6 ENTRADA HACIENDA SAN MIGUEL, CHOLOMA CORTES',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(423,'JC INTERNATIONAL LAUNDRY II','ZOLI JC RIO BLANQUITO',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(89,'JC SEWING SUPPLY','ZIP RIO BLANCO, EDIFICIO No.12',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(441,'JERZEES BUENA VISTA','ZOLI ZIP BUENA VISTA, VILLANUEVA CORTES',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(870,'JERZEES NUEVO DIA','ZIP CHOLOMA NAVE B',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(271,'JIN_HO HONDURAS','CARRETERA A OCCIDENTE KM19.5 NACO QUIMISTAN, SANTA BARBARA',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(864,'JOCKEY DE HONDURAS','ZIP BUFALO',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(131,'JOGBRA DE HONDURAS, S.A.','ZOLI ZIP BUENA VISTA, VILLANUEVA',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(159,'JOSE FILADELFO GARCIA','SAN PEDRO SULA, CORTES, HONDURAS',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(1030,'KENTEX','ZOLI INHDELVA SUR 800 MTS. CARRETERA A LA JUTOSA',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(861,'KIT MANUFACTURING S DE RL','NULL',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(830,'KIT TEXTILES','NULL',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(966,'LA ARROCERA','NULL',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(1057,'LA CEIBA','MUELLE DE CABOTAJE LA CEIBA',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(1129,'LACTEOS DE HONDURAS','NULL',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(130,'LAND APPAREL, S.A.','ZOLI PUERTO CORTES, EDIF. No.6',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(394,'LANE EXPORT GROUP S. DE R.L.','ZOLI RIO BLANCO, EDIFICIO #25',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(868,'MAC SA','INDUSTRIAL PARK BUFALO PO BOX 10555 BUFALO VILLANUEVA',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(1046,'MAG','ZOLI INHDELVA ESTE 800 MTS. CARRETERA A LA JUTOSA',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(725,'MANTEX DE HONDURAS','ZIP CHOLOMA',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(1178,'MANUCHAR HONDURAS S.A. DE C.V.','PLAZA MARITIMA 4 CALLE SAN PEDRO SULA, CORTÉS HONDURAS',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(913,'MANUFACTURERA DEL TROPICO','NULL',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(136,'MANUFACTURERA DEL VALLE S.A','ZIP RIO BLANCO EDIFICIO 29',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(595,'MANUFACTURERA SAN PEDRO SULA S.de R.L.','ZIP BUENA VISTA, VILLANUEVA CORTES',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(1090,'MARTEX FIBER INTERNATIONAL','KM 2.5 AUTOPISTA A PTO CORTES CHOLOMA',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(525,'MASECA','AUTOPISTA A PUERTO CORTES',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(404,'MATEX DE HONDURAS','ZIP CALPULES,CARRETERA A LA LIMA EDIFICIO 8 S.P.S',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(961,'MAXI BODEGA','AUTOPISTA HACIA PTO. CORTES, MALL LAS AMERICAS',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(454,'MAYA TRADING GROUP','ZIP MAYA TRADING COL. BOGRAN SPS',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(313,'MECANIZACIONES VELASQUEZ','BARRIO EL BENQUE SAN PEDRO SULA, HONDURAS',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(194,'MECANIZACIONES WILLIAMS','CHOLOMA, CORTES.',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(806,'MERRIL S.A.','ZOLI INHDELVA ESTE 800 MTS. CARRETERA A LA JUTOSA',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(1133,'METALES Y ALEACIONES','NULL',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(69,'METALES Y MAS','AVE. CIRCUNVALACION, FRENTE A CITY MALL',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(853,'MEXICO','NULL',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(1019,'MOLINO HARINERO','SAN PEDRO SULA',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(869,'MONKEY INTERNATIONAL APPAREL S. DE R.L.','ZOLI RIO BLANCO EDFICIO No.40 SALIDA HACIA PTO CORTES',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(692,'MORRISETTE WAYNE DE C.A. S DE R.L.','ZIP BUFALO , EDIFICO 1B',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(916,'MRK','ZOLI INHDELVA ESTE 800 MTS. CARRETERA A LA JUTOSA',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(1009,'MUNICIPALIDAD OLANCHITO','NULL',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(58,'N Y F GARMENT','ZOLI EL CARMEN, SALIDA A LA LIMA, SPS',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(1174,'NANOWIN','ZOLI INHDELVA NORTE 800 MTS. CARRETERA A LA JUTOSA',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(442,'NAZDAR CENTRAL AMERICA','ZIP BUFALO',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(1051,'NESTLE HONDUREÑA S.A.','CARRETERA AL POLVORÍN INTERSECCIÓN BLVD. DEL ESTE COMPLEJO MACRO BODEGAS DIUNSA, CONTIGUO A FUNDACIÓN MHOTIVO SAN PEDRO SULA, CORTÉS, HONDURA',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(467,'NEW APPAREL S. DE R.L.','ZOLI ZIP RIO BLANCO',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(829,'NEW BUFALO CENTRAL AMERIC','GREEN VALLEY INDUSTRIAL PARK, CARRETERA A OCCIDENTE, KM. 23 QUIMISTAN, SANTA BARBARA, HONDURAS',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(20,'NEW HOLLAND LINGERIE DE HONDURAS','ZOLI NEW HOLLAND',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(826,'NICARAGUA','NICARAGUA',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(91,'NOVACHEM','ZONA LIBRE PARQUE INDUSTRIAL CASTILLO',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(922,'NOVALACE','QUIMICAS HANDAL KM 2.6 AUTOPISTA A PUERTO CORTÉS, CHOLOMA CORTÉS, HONDURAS, C.A',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(5,'NOW HONDURAS, S.A. DE C.V.','ZONA LIBRE ASTRO HONDURAS, COL. FELIPE ZELAYA, SPS; HONDURA',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(1044,'OLANCHO','ZONA ORIENTAL AL NORESTE DEL PAÍS',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(831,'ONTEX S.A.','ZOLI REAL',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(880,'PACAS DE HONDURAS','',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(952,'PACASA','SAN PEDRO SULA',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(1016,'PANAMA','SURESTE DE AMÉRICA CENTRAL',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(1134,'PAPELERA CALPULES','VILLANUEVA',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(991,'PARKDALE','GREEN VALLEY INDUSTRIAL PARK CARRETERA A OCCIDENTE KM 24 QUIMISTAN HONDURAS ',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(109,'PAXAR DE HONDURAS','ZIP BUFALO, VILLANUEVA CORTES.',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(70,'PETRALEX','ZOLI BUFALO, VILLANUEVA, CORTES',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(485,'PHOENIX DE HONDURAS','ZOLI HONDURAS',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(163,'PINDU LIMITADA','ZOLI C.B.I. LA CEIBA',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(140,'PINEHURST MANUFACTURING','ZOLI ZIP CALPULES KM 7 CARRETERA A LA LIMA',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(197,'PLASTIFORM, S.A.','ZOLI ZIP CALPULES, KM 7, SALIDA A LA LIMA',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(1006,'PLYCEM CONSTRUSISTEMAS HONDURAS','VILLANUEVA',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(850,'PREDIO CHOLOMA','CHOLOMA',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(821,'PREDIO CORTES','CORTES',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(1108,'PREDIO DOLE','CORTES',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(937,'PREDIO HAPAG LLOYD','1 Y 2 AVE. 4 CALLE , EDIFICIO PLAZA MARÍTIMA SAN PEDRO SULA, HONDURAS C.A',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(953,'PREDIO PUMA VILLANUEVA','VILLANUEVA',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(820,'PREDIO SAN PEDRO SULA','SAN PEDRO SULA',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(65,'PREDIO ZALDIVAR','CHOLOMA',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(344,'PREMIER, S.A.','ZOLI ZIP BUFALO,EDIFICIO# 8 VILLANUEVA CORTES.',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(478,'PRESTIGIE','ZIP FORMOSA KM. 11 CARRETERA A OCC. FRENTE COL. SAN JORGE',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(385,'PRIDE MANUFACTURING','ZOLI HONDURAS',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(1117,'PRIDE PERFORMANCE','KM. 19.5 CARRETERA A OCCIDENTE LA ACEQUIA QUIMISTAN, NACO SANTA BÁRBARA, HONDURAS',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(1172,'PRIDE TEXTILES','ZOLI AMERICA',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(1171,'PRIDE YARN S. de R.L.','ZIP HONDURAS, CARRETERA A PTO. CORTES',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(1062,'PROCARGO AGENCY','Bº EL BENQUE 11 AVE. 5 Y 6 CALLE S.O. SAN PEDRO SULA CORTÉS (HONDURAS)',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(107,'PROCESOS INDUSTRIALES','BARRIO BERMEJO FRENTE AL BORDO SPS',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(475,'PROCHEM HONDURAS, S.A.','2DO ANILLO PERIFERICO ZIP SAN JOSE SPS',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(1118,'PRODUCTORA DE ALIMENTOS','ZELAYA, SAN PEDRO SULA, HONDURAS',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(768,'PRODUCTOS INDUSTRIALES S.A (PRISA)','ZONA LIBRE METROPOLITANA JACALEAPA TEGUCIGALPA',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(23,'PRODUCTOS TEXTILES, S.A. DE C.V.','ZOLI INHDELVA NORTE 800 MTS. CARRETERA A LA JUTOSA',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(903,'PROYECTO HIDROELECTRICO CHAMELECON','MUNICIPIO DE MACUELIZO, SANTA BÁRBARA.',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(1058,'PTO CASTILLA','BAHÍA DE TRUJILLO EN LA COSTA ATLÁNTICA A 16º00´00´´ LATITUD NORTE Y 86º01´00´´ LONGITUD OESTE.',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(223,'PULIDORA MORALES','COL. LA LOPEZ, CHOLOMA, CORTES',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(882,'QUIMICAS HANDAL','KM 2.6 AUTOPISTA A PUERTO CORTÉS, CHOLOMA CORTÉS, HONDURAS, C.A',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(824,'R & M MANUFACTURING','R & M MANUFACTURING',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(542,'R.K.I.','ZOLI ZIP BUENA VISTA, NAVES FGI FG2, VILLANUEVA, HONDURAS',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(947,'RECICLADORA EUROTEXTIL','NULL',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(446,'RECICLADORES DE HONDURAS','HONDURAS C.A.',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(60,'RECTEX DE HONDURAS','SALIDA A PUERTO CORTES, KM 1, CALLEJON BOCOCK 40 MTS HACIA DENTRO POR CAMAS DINA, INVERSIONES LA VICTORIA, CHOLOMA CORTES',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(367,'REPARACION ELECTRONICA INDUSTRIAL','4 Y 5 CALLE, EDIFICIO NOVA PLAZA CHOLOMA',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(799,'REPUESTOS SINAI','ZOLI INHDELVA SUR 800 MTS. CARRETERA A LA JUTOSA',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(300,'RIO GARMENT S DE R. L','KM 7 CARRETERA A PTO.CORTES ZIP RIO BLANCO',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(1033,'RKI DE HONDURAS','ZP VILLANUEVA',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(222,'RLA MANUFACTURING S. DE R.L.','2.5 KM CARRETERA A LA JUTOSA ZOLI LA JUTOSA CHOLOMA, CORTES ',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(862,'ROATAN VILLANUEVA','VILLANUEVA',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(842,'ROMAN KNITS','NULL',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(484,'S & P RECYCLING HONDURAS S.A','ZIP CHAMELECON DESVIO AL CALAN VILLANUEVA CORTES',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(943,'S&S DE HONDURAS','CARRETERA HACIA LA LIMA KM#7 EDIFICIO 3-A',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(630,'S.E.C.','ZIP HONDURAS, KM 5 CARRETERA A PUERTO CORTES',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(1001,'SANTA CRUZ DE YOJOA','NULL',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(907,'SANTA ROSA DE COPAN','NULL',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(268,'SAVITEX HONDURAS S.A DE C.V','ZOLI INHDELVA ESTE 800 MTS. CARRETERA A LA JUTOSA',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(276,'SE MYEONG APPAREL','ZONA LIBRE EL CARMEN, CARRETERA VIEJA LA LIMA',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(9,'SEJIN, S.A.','PARQUE INDUSTRIAL REAL, CHOLOMA, CORTES; HOND.',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(214,'SEMSU','ZOLI ELCA CHOLOMA CORTES',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(233,'SEPRISA','',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(366,'SERTEX S. DE R. L.','ZOLI FORMOSA',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(215,'SERVOTECHNOLOGY, S.A.','1ERA AVE. 1ERA CALLE, SAN PEDRO SULA',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(133,'SETISA','ZOLI ZIP HONDURAS',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(977,'SIGUATEPEQUE','NULL',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(629,'SIMTEX INTERNATIONAL','CARRETERA OCCIDENTE KM 23 ZOLI GREEN VALLEY QUIMISTAN STA BARBARA',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(22,'SKIPS DE HONDURAS','EDIFICIO 10 VILLANUEVA, HONDURAS',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(974,'SOCIEDAD GENERAL DEL ACERO S.A.','COLONIA ALTAMIRA 17 CALLE 23 AVENIDA, CASA # 7C SAN PEDRO SULA, CORTÉS HONDURAS',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(248,'SODIPRO,S. DE R.L','COL. LUSIANA,33CLL.27 AVE,BLOQUE "C".',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(1110,'SOLATEX HONDURAS','ZOLI INDUSTRIAL RIO BLANCO',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(384,'SOUTHERN APPAREL','BOULEVAR DEL SUR KM 71/12 SAN PEDRO SULA CORTES',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(563,'STAR S. A.','ZIP EL PORVENIR KM 7 CARRETERA A TELA',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(802,'STARCHEM','ZOLI INHDELVA SUR 800 MTS. CARRETERA A LA JUTOSA',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(997,'STRETCHLINE C. A. ZL ELCATEX','ZOLI ELCATEX CHOLOMA, CORTES',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(1101,'SUMINISTROS INDUSTRIALES','NULL',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(52,'T. A. APPAREL, S.A.','ZOLI BARACOA, AUTOPISTA A PTO. CORTES',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(425,'TABUSCH MANUFACTURING','ZIP BUENA VISTA CARRT A TEGUS, VILLANUEVA',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(992,'TALLER CELIN ZELAYA','NULL',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(85,'TALLER MAITEC','SAN PEDRO SULA.',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(37,'TALLER WILMER MORALES','COL. MONTE ALEGRE, ATRAS COL. JUAN RAMON MOLINA',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(1002,'TECNO SUPPLIER','CHOLOMA, CORTES',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(112,'TECNOLOGIAS COMERCIALES S.A. DE C.V.','ZOLI EL CARMEN',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(828,'TEGUCIGALPA','NULL',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(944,'TELA PLANT','ZIP EL PORVENIR KM. 7 CARRETERA A TELA, EL PROGRESO, YORO HONDURAS',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(948,'TELAS ELASTICAS','ZL GREEN VALLEY NACO SANTA BARBARA',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(936,'TERA CHEMEMICALS CORPORATION S.A.','ZOLI INHDELVA NORTE 800 MTS. CARRETERA A LA JUTOSA',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(224,'TEXTILES DEL CARIBE','VILLANUEVA INDUSTRIAL PARK, VILLANUEVA, CORTES.',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(54,'TEXTILES SUPPLY AND SERVICES','ZOLI TEXTILE SUPPLY, COL. RIVERA H. SPS',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(516,'THREAD AND TRIM SUPPLIERS','ZOLI HONDURAS KM 5 CARRETERA A PUERTO CORTES',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(187,'TOLEDO CUTTING','ZOLI E INVERSIONES LAS FLORES CARRETERA A PUERTO CORTES, KM. 14, QUEBRADA SECA, CHOLOMA, CORTES , HONDURAS',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(1140,'TOPITEX','ZIP CHOLOMA II CARRETERA LA JUTOSA CHOLOMA HN',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(398,'TRANS EXPRESS','12 AVE, 8CALLE, N.O. LOS ANDES',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(855,'TRANSPORTES Y SERVICIOS MUÑOZ','COL. EL ESTADIO FRENTE A GASOLINERA UNO 33 CALLE EL POLVORIN',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(8,'TRHEE H, S.A. DE C.V.','CARRETERA A OMOA, FRENTE A INST. FRANKLIN, PUERTO CORTES',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(1017,'TRUJILLO','DEPARTAMENTO DE COLÓN, HONDURAS',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(307,'UNION PLASTIC & PACK S. DE R.L','KM.11 CARRETERA A OCCIDENTE, COL. SAN JORGE, COFRADIA, SPS',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(49,'VAN HEUSEN DE CENTROAMERICA','AVE JUAN PABLO II, 2 Y CALLE SAN PEDRO SULA',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(960,'VESTA TRADING','ZOLI INHDELVA NORTE 800 MTS. CARRETERA A LA JUTOSA',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(769,'VFI DE HONDURAS','2.5 KM CARRETERA A LA JUTOSA ZOLI LA JUTOSA CHOLOMA, CORTES ',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(302,'VIAFIL HONDURAS S.A','ZOLI INHDELVA ESTE 800 MTS. CARRETERA A LA JUTOSA',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(852,'WOONG CHUN HONDURAS','KM 195 CARRETERA A OCCIDENTE SANTA BARBARA HONDURAS',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(25,'YANGTEX S.A.','ZOLI FORMOSA, KM 11, CARRETERA A OCCIDENTE',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(422,'YIKAMA S. DE R.L.','ZOLI YIKAMA',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(149,'YKK HONDURAS S.A','SALIDA VIEJA A LA LIMA. SPS',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(309,'YOO YANG S.A.','ZOLI CONTINENTAL, LA LIMA , CORTES',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(408,'YOU HONG KIM','TOLEDO CUTTING ZONA LIBRE TOLEDO KM5 BOULEVARD A PUERTO COR',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(801,'ZABCORD','ZOLI INHDELVA ESTE 800 MTS. CARRETERA A LA JUTOSA',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(836,'ZIP BUENA VISTA','VILLANUEVA',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(362,'ZIP BUFALO','VILLANUEVA',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(846,'ZIP CALPULES','AUTOPISTA A 3 KMS. DEL AEROPUERTO INTERNACIONAL "RAMON VILLEDA MORALES"',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(585,'ZIP CHOLOMA','CARRETERA HACIA PUERTO CORTÉS, ENTRADA PRINCIPAL COL. LA MORA, ENFRENTE DE MALL LAS AMERICAS, CHOLOMA, CORTÉS',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(1025,'ZIP CHOLOMA II','CARRETERA LA JUTOSA CHOLOMA HN',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(835,'ZIP PORVENIR','KM. 7 CARRETERA A TELA, EL PROGRESO, YORO HONDURAS',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(898,'ZIP RIO BLANCO','BULEVAR DEL NORTE., SAN PEDRO SULA 21102',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(415,'ZIP SAN JOSE','20 CALLE SE, SAN PEDRO SULA',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(859,'ZIP VILLANUEVA','CA-5, VILLANUEVA',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(844,'ZOLI AMERICA','KM. 6, AUTOPISTA SAN PEDRO SULA, CORTÉS-TRINCHERAS, CHOLOMA, CORTÉS',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(497,'ZOLI CIRSA HONDURAS','BULEVAR DEL SUR SECTOR DOS CAMINOS VILLANUEVA CORTES HONDURAS',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(1135,'ZOLI COFRADIA INDUSTRIAL PARK S.A.','COFRADIA ,CORTES HONDURAS ',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(881,'ZOLI EL CARMEN','NULL',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(604,'ZOLI EL POLVORIN','CARRETERA AL POLVORIN ATRÁS DE TRANYCOP, CORTÉS, SAN PEDRO SULA, HONDURAS',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(867,'ZOLI GILDAN RIO NANCE','NULL',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(317,'ZOLI HONDURAS','CARRETERA A CHOLOMA ,CORTES HONDURAS',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(832,'ZOLI INVERSIONES LAS FLORES','CARRETERA A PUERTO CORTES, KM. 14, QUEBRADA SECA, CHOLOMA, CORTES , HONDURAS',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(969,'ZOLI LA VICTORIA','CHOLOMA, CORTES',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(940,'ZOLI LEAR AUTOMOTIVE','SAN PEDRO SULA, HONDURAS COFRADÍA, NACO, MUNICIPIO DE QUIMISTÁN',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(839,'ZOLI METROPOLITANA JACALEAPA','ZONA LIBRE METROPOLITANA, JACALEAPA FRENTE A COL HONDURAS, TEGUCIGALPA, HONDURAS',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(783,'ZOLI REAL','CARRETERA A LA JUTOSA FRENTE A GASOLINERA TEXACO',5,1)
INSERT INTO dbo.Companies(code,Name,Address,RegionId,IsActive) Values(605,'ZOLI TSS','CARRETERA A TICAMAYA, ENTRE 12-14 CALLE PRADOS ATRAS DE LA MEGAPOSTA',5,1)


INSERT INTO dbo.SecuritySupervisors(Name,IsActive) Values('CARLOS CHACON',1)
INSERT INTO dbo.SecuritySupervisors(Name,IsActive) Values('CARLOS GARCIA',1)
INSERT INTO dbo.SecuritySupervisors(Name,IsActive) Values('DANYS AGUILAR',1)
INSERT INTO dbo.SecuritySupervisors(Name,IsActive) Values('ISMAEL CANALES',1)
INSERT INTO dbo.SecuritySupervisors(Name,IsActive) Values('JACOBO ALVARADO',1)
INSERT INTO dbo.SecuritySupervisors(Name,IsActive) Values('JOSE  CASTILLO',1)
INSERT INTO dbo.SecuritySupervisors(Name,IsActive) Values('JUAN OLIVA',1)
INSERT INTO dbo.SecuritySupervisors(Name,IsActive) Values('JUNIOR PINEDA',1)
INSERT INTO dbo.SecuritySupervisors(Name,IsActive) Values('MANUEL CASTILLO',1)
INSERT INTO dbo.SecuritySupervisors(Name,IsActive) Values('NOLVIN PAGUADA',1)
INSERT INTO dbo.SecuritySupervisors(Name,IsActive) Values('OLVIN MONCADA',1)
INSERT INTO dbo.SecuritySupervisors(Name,IsActive) Values('OSCAR GUTIERREZ',1)
INSERT INTO dbo.SecuritySupervisors(Name,IsActive) Values('RAFAEL ALVAREZ',1)
INSERT INTO dbo.SecuritySupervisors(Name,IsActive) Values('RUFINO AVILA',1)
INSERT INTO dbo.SecuritySupervisors(Name,IsActive) Values('SELVIN FUNEZ',1)
INSERT INTO dbo.SecuritySupervisors(Name,IsActive) Values('WILSON MADRID',1)

INSERT into dbo.Drivers(CardId,Name,IsActive) Values('0801-1991-15809','ALDO ACOSTA',1)
INSERT into dbo.Drivers(CardId,Name,IsActive) Values('0506-1984-02431','ALEXIS MARTEL',1)
INSERT into dbo.Drivers(CardId,Name,IsActive) Values('1701-1970-00939','ALEXIS CONTRERAS',1)
INSERT into dbo.Drivers(CardId,Name,IsActive) Values('0501-1981-11792','ANDRES MURILLO',1)
INSERT into dbo.Drivers(CardId,Name,IsActive) Values('1501-1967-00082','ARMANDO MATUTE',1)
INSERT into dbo.Drivers(CardId,Name,IsActive) Values('0318-1989-00403','ARNOL MARTINEZ',1)
INSERT into dbo.Drivers(CardId,Name,IsActive) Values('1808-1973-00319','BENJAMIN PORTILLO',1)
INSERT into dbo.Drivers(CardId,Name,IsActive) Values('1601-1976-01033','BERTILIO TERUEL',1)
INSERT into dbo.Drivers(CardId,Name,IsActive) Values('081-240958-0002-G','CAIRO ACEVEDO',1)
INSERT into dbo.Drivers(CardId,Name,IsActive) Values('1501-1980-02958','CARLOS ACOSTA',1)
INSERT into dbo.Drivers(CardId,Name,IsActive) Values('0318-1985-00908','CARLOS LEIVA',1)
INSERT into dbo.Drivers(CardId,Name,IsActive) Values('0501-1983-08545','CARLOS LOPEZ',1)
INSERT into dbo.Drivers(CardId,Name,IsActive) Values('0824-1974-00051','CARLOS LUQUE',1)
INSERT into dbo.Drivers(CardId,Name,IsActive) Values('0502-1987-00651','CARLOS MARTEL',1)
INSERT into dbo.Drivers(CardId,Name,IsActive) Values('1804-1958-00795','CARLOS SUAZO',1)
INSERT into dbo.Drivers(CardId,Name,IsActive) Values('0801-1984-20513','CORY LAGOS',1)
INSERT into dbo.Drivers(CardId,Name,IsActive) Values('0501-1968-03847','DAVID OCHOA',1)
INSERT into dbo.Drivers(CardId,Name,IsActive) Values('0819-1975-00049','DENIS FUENTES',1)
INSERT into dbo.Drivers(CardId,Name,IsActive) Values('0501-1982-02929','DENIS ZAPATA',1)
INSERT into dbo.Drivers(CardId,Name,IsActive) Values('1807-1975-01364','DENNIS BERNARDEZ',1)
INSERT into dbo.Drivers(CardId,Name,IsActive) Values('0803-1996-00113','DOUGLAS ALVARENGA',1)
INSERT into dbo.Drivers(CardId,Name,IsActive) Values('0501-1990-04404','DOUGLAS OSORIO',1)
INSERT into dbo.Drivers(CardId,Name,IsActive) Values('0803-1985-00511','EBER ALVARENGA',1)
INSERT into dbo.Drivers(CardId,Name,IsActive) Values('0506-2001-02397','EDDY BAHR',1)
INSERT into dbo.Drivers(CardId,Name,IsActive) Values('0808-1991-00371','EDELMIN ARGUETA',1)
INSERT into dbo.Drivers(CardId,Name,IsActive) Values('0301-1979-00525','EDINSON GUILLEN',1)
INSERT into dbo.Drivers(CardId,Name,IsActive) Values('0502-1988-0321','EDUARDO CABRERA',1)
INSERT into dbo.Drivers(CardId,Name,IsActive) Values('1307-1983-00302','EDWIN HERNANDEZ',1)
INSERT into dbo.Drivers(CardId,Name,IsActive) Values('0502-1982-01836','EFER CRIBAS',1)
INSERT into dbo.Drivers(CardId,Name,IsActive) Values('1804-1985-02417','ELIAS AYALA',1)
INSERT into dbo.Drivers(CardId,Name,IsActive) Values('0502-1940-00064','ENCARNACION CRIBAS',1)
INSERT into dbo.Drivers(CardId,Name,IsActive) Values('0803-1991-00036','ERIC ALVARENGA',1)
INSERT into dbo.Drivers(CardId,Name,IsActive) Values('0502-1984-01795','EVER DIAZ',1)
INSERT into dbo.Drivers(CardId,Name,IsActive) Values('1801-1949-00004','FAUSTINO HERNANDEZ',1)
INSERT into dbo.Drivers(CardId,Name,IsActive) Values('0510-1975-00806','FREDY PEÑA',1)
INSERT into dbo.Drivers(CardId,Name,IsActive) Values('0803-1958-00330','GUILLERMO ALVARENGA',1)
INSERT into dbo.Drivers(CardId,Name,IsActive) Values('0501-1986-02438','HECTOR ARITA',1)
INSERT into dbo.Drivers(CardId,Name,IsActive) Values('1806-1956-00261','INOCENTE URBINA',1)
INSERT into dbo.Drivers(CardId,Name,IsActive) Values('0501-1980-07224','JAVIER ORELLANA',1)
INSERT into dbo.Drivers(CardId,Name,IsActive) Values('1804-1981-00427','JOEL FAJARDO',1)
INSERT into dbo.Drivers(CardId,Name,IsActive) Values('0509-1979-00204','JOSE ALVARADO',1)
INSERT into dbo.Drivers(CardId,Name,IsActive) Values('0501-1952-02263','JOSE BU',1)
INSERT into dbo.Drivers(CardId,Name,IsActive) Values('0511-1996-10015','JOSE CANACA',1)
INSERT into dbo.Drivers(CardId,Name,IsActive) Values('0210-271249-102-1','JOSE FLORES',1)
INSERT into dbo.Drivers(CardId,Name,IsActive) Values('0501-1973-02766','JOSE GOMEZ',1)
INSERT into dbo.Drivers(CardId,Name,IsActive) Values('0422-1981-00202','JOSE MARTINEZ',1)
INSERT into dbo.Drivers(CardId,Name,IsActive) Values('0501-1950-01214','JOSE RAMOS',1)
INSERT into dbo.Drivers(CardId,Name,IsActive) Values('0501-1965-08982','JUAN LOPEZ',1)
INSERT into dbo.Drivers(CardId,Name,IsActive) Values('0502-1972-01339','JUAN MORALES',1)
INSERT into dbo.Drivers(CardId,Name,IsActive) Values('0502-1987-02044','KEVEN BELTRAN',1)
INSERT into dbo.Drivers(CardId,Name,IsActive) Values('0506-1991-01442','KEVIN BAHR',1)
INSERT into dbo.Drivers(CardId,Name,IsActive) Values('0502-1982-01738','LUCAS DIAZ',1)
INSERT into dbo.Drivers(CardId,Name,IsActive) Values('0502-1993-01685','MANUEL VASQUEZ',1)
INSERT into dbo.Drivers(CardId,Name,IsActive) Values('0210-060868-103-7','MARIO RODRIGUEZ',1)
INSERT into dbo.Drivers(CardId,Name,IsActive) Values('0101-1979-00752','MAURICIO LOPEZ',1)
INSERT into dbo.Drivers(CardId,Name,IsActive) Values('0502-1981-02078','MOISES FIGUEROA',1)
INSERT into dbo.Drivers(CardId,Name,IsActive) Values('1801-1968-00566','NAHUN CALIX',1)
INSERT into dbo.Drivers(CardId,Name,IsActive) Values('0314-1975-00034','NOE AMAYA',1)
INSERT into dbo.Drivers(CardId,Name,IsActive) Values('0302-1983-00140','NOE HERNANDEZ',1)
INSERT into dbo.Drivers(CardId,Name,IsActive) Values('0502-1976-00830','OSCAR FIGUEROA',1)
INSERT into dbo.Drivers(CardId,Name,IsActive) Values('0501-1970-07310','RAFAEL PEÑA',1)
INSERT into dbo.Drivers(CardId,Name,IsActive) Values('0502-1947-02271','RAFAEL TALAVERA',1)
INSERT into dbo.Drivers(CardId,Name,IsActive) Values('0501-1981-08467','RICARDO PEREA',1)
INSERT into dbo.Drivers(CardId,Name,IsActive) Values('0107-1987-03090','SAUL PAZ',1)
INSERT into dbo.Drivers(CardId,Name,IsActive) Values('0506-1977-01799','SELVIN RODRIGUEZ',1)
INSERT into dbo.Drivers(CardId,Name,IsActive) Values('0502-1987-00033','SERGIO FAJARDO',1)
INSERT into dbo.Drivers(CardId,Name,IsActive) Values('0302-1983-00086','TULIO FONSECA',1)
INSERT into dbo.Drivers(CardId,Name,IsActive) Values('0107-1974-01651','WILFREDO GUERRA',1)
INSERT into dbo.Drivers(CardId,Name,IsActive) Values('0506-1977-00629','WILSON VELASQUEZ',1)

